apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: basic
spec:
  version: v6.3.0
  timezone: UTC
  pvReclaimPolicy: Delete
  pd:
    baseImage: pingcap/pd
    replicas: 1
    maxFailoverCount: 0
    requests:
      storage: "1Gi"
    config: {}
  tikv:
    baseImage: pingcap/tikv
    replicas: 1
    maxFailoverCount: 0
    requests:
      storage: "1Gi"
    config:
      storage:
        reserve-space: "0MB"
      rocksdb:
        max-open-files: 256
      raftdb:
        max-open-files: 256
  tidb:
    baseImage: xhebox/tidb
    version: latest
    replicas: 1
    imagePullPolicy: Always
    maxFailoverCount: 0
    service:
      type: ClusterIP
    config: |
      [security]
      session-token-signing-cert = "/var/sess/cert.pem"
      session-token-signing-key = "/var/sess/key.pem"
    additionalVolumes:
      - name: "sess"
        secret:
          secretName: basic-sess
          items:
            - key: crt
              path: cert.pem
            - key: key
              path: key.pem
    additionalVolumeMounts:
    additionalVolumeMounts:
      - name: "sess"
        mountPath: /var/sess
        readOnly: false
  tiproxy:
    baseImage: xhebox/tiproxy
    version: latest
    imagePullPolicy: Always
    replicas: 1
    requests:
      storage: "1Gi"
