---
apiVersion: v1
kind: ConfigMap
metadata:
  name: debug-proxy
data:
  3proxy.cfg: |
    log
    auth none
    proxy -p3128
    socks -p1080
    monitor /etc/3proxy/cfg/3proxy.cfg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-proxy
spec:
  selector:
    matchLabels:
      app: k8s-resource-provider
      name: proxy
  template:
    metadata:
      labels:
        app: k8s-resource-provider
        name: proxy
    spec:
      containers:
      - name: proxy
        image: riftbit/3proxy
        ports:
        - containerPort: 3128
          protocol: TCP
        - containerPort: 1080
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/3proxy/cfg
      volumes:
      - name: config
        configMap:
          name: debug-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: debug-proxy
spec:
  type: NodePort
  selector:
    app: k8s-resource-provider
    name: proxy
  ports:
  - name: http
    port: 3128
    protocol: TCP
  - name: socks5
    port: 1080
    protocol: TCP
